# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shard_node_pb2 as shard__node__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shard_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Apply = channel.unary_unary(
                '/week09shard.ShardNode/Apply',
                request_serializer=shard__node__pb2.ApplyRequest.SerializeToString,
                response_deserializer=shard__node__pb2.ApplyResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/week09shard.ShardNode/Read',
                request_serializer=shard__node__pb2.ReadRequest.SerializeToString,
                response_deserializer=shard__node__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.GetShardDump = channel.unary_unary(
                '/week09shard.ShardNode/GetShardDump',
                request_serializer=shard__node__pb2.GetShardDumpRequest.SerializeToString,
                response_deserializer=shard__node__pb2.GetShardDumpResponse.FromString,
                _registered_method=True)
        self.LoadShardDump = channel.unary_unary(
                '/week09shard.ShardNode/LoadShardDump',
                request_serializer=shard__node__pb2.LoadShardDumpRequest.SerializeToString,
                response_deserializer=shard__node__pb2.LoadShardDumpResponse.FromString,
                _registered_method=True)
        self.DropShard = channel.unary_unary(
                '/week09shard.ShardNode/DropShard',
                request_serializer=shard__node__pb2.DropShardRequest.SerializeToString,
                response_deserializer=shard__node__pb2.DropShardResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/week09shard.ShardNode/Status',
                request_serializer=shard__node__pb2.StatusRequest.SerializeToString,
                response_deserializer=shard__node__pb2.StatusResponse.FromString,
                _registered_method=True)


class ShardNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShardDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadShardDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=shard__node__pb2.ApplyRequest.FromString,
                    response_serializer=shard__node__pb2.ApplyResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=shard__node__pb2.ReadRequest.FromString,
                    response_serializer=shard__node__pb2.ReadResponse.SerializeToString,
            ),
            'GetShardDump': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShardDump,
                    request_deserializer=shard__node__pb2.GetShardDumpRequest.FromString,
                    response_serializer=shard__node__pb2.GetShardDumpResponse.SerializeToString,
            ),
            'LoadShardDump': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadShardDump,
                    request_deserializer=shard__node__pb2.LoadShardDumpRequest.FromString,
                    response_serializer=shard__node__pb2.LoadShardDumpResponse.SerializeToString,
            ),
            'DropShard': grpc.unary_unary_rpc_method_handler(
                    servicer.DropShard,
                    request_deserializer=shard__node__pb2.DropShardRequest.FromString,
                    response_serializer=shard__node__pb2.DropShardResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=shard__node__pb2.StatusRequest.FromString,
                    response_serializer=shard__node__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'week09shard.ShardNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('week09shard.ShardNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/Apply',
            shard__node__pb2.ApplyRequest.SerializeToString,
            shard__node__pb2.ApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/Read',
            shard__node__pb2.ReadRequest.SerializeToString,
            shard__node__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShardDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/GetShardDump',
            shard__node__pb2.GetShardDumpRequest.SerializeToString,
            shard__node__pb2.GetShardDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadShardDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/LoadShardDump',
            shard__node__pb2.LoadShardDumpRequest.SerializeToString,
            shard__node__pb2.LoadShardDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/DropShard',
            shard__node__pb2.DropShardRequest.SerializeToString,
            shard__node__pb2.DropShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09shard.ShardNode/Status',
            shard__node__pb2.StatusRequest.SerializeToString,
            shard__node__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
