# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import week09_gateway_pb2 as week09__gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in week09_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Week09GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSection = channel.unary_unary(
                '/week09.Week09Gateway/CreateSection',
                request_serializer=week09__gateway__pb2.CreateSectionRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.CreateSectionResponse.FromString,
                _registered_method=True)
        self.Enroll = channel.unary_unary(
                '/week09.Week09Gateway/Enroll',
                request_serializer=week09__gateway__pb2.EnrollRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Drop = channel.unary_unary(
                '/week09.Week09Gateway/Drop',
                request_serializer=week09__gateway__pb2.DropRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.DropResponse.FromString,
                _registered_method=True)
        self.GetStudentSchedule = channel.unary_unary(
                '/week09.Week09Gateway/GetStudentSchedule',
                request_serializer=week09__gateway__pb2.GetStudentScheduleRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.GetStudentScheduleResponse.FromString,
                _registered_method=True)
        self.GetSectionRoster = channel.unary_unary(
                '/week09.Week09Gateway/GetSectionRoster',
                request_serializer=week09__gateway__pb2.GetSectionRosterRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.GetSectionRosterResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/week09.Week09Gateway/CreateAccount',
                request_serializer=week09__gateway__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/week09.Week09Gateway/GetAccount',
                request_serializer=week09__gateway__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/week09.Week09Gateway/Transfer',
                request_serializer=week09__gateway__pb2.TransferRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.CreateInventoryItem = channel.unary_unary(
                '/week09.Week09Gateway/CreateInventoryItem',
                request_serializer=week09__gateway__pb2.CreateInventoryItemRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.CreateInventoryItemResponse.FromString,
                _registered_method=True)
        self.ReserveItem = channel.unary_unary(
                '/week09.Week09Gateway/ReserveItem',
                request_serializer=week09__gateway__pb2.ReserveItemRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.ReserveItemResponse.FromString,
                _registered_method=True)
        self.ReleaseReservation = channel.unary_unary(
                '/week09.Week09Gateway/ReleaseReservation',
                request_serializer=week09__gateway__pb2.ReleaseReservationRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.ReleaseReservationResponse.FromString,
                _registered_method=True)
        self.GetInventory = channel.unary_unary(
                '/week09.Week09Gateway/GetInventory',
                request_serializer=week09__gateway__pb2.GetInventoryRequest.SerializeToString,
                response_deserializer=week09__gateway__pb2.GetInventoryResponse.FromString,
                _registered_method=True)


class Week09GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSectionRoster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInventoryItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Week09GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSection,
                    request_deserializer=week09__gateway__pb2.CreateSectionRequest.FromString,
                    response_serializer=week09__gateway__pb2.CreateSectionResponse.SerializeToString,
            ),
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=week09__gateway__pb2.EnrollRequest.FromString,
                    response_serializer=week09__gateway__pb2.EnrollResponse.SerializeToString,
            ),
            'Drop': grpc.unary_unary_rpc_method_handler(
                    servicer.Drop,
                    request_deserializer=week09__gateway__pb2.DropRequest.FromString,
                    response_serializer=week09__gateway__pb2.DropResponse.SerializeToString,
            ),
            'GetStudentSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentSchedule,
                    request_deserializer=week09__gateway__pb2.GetStudentScheduleRequest.FromString,
                    response_serializer=week09__gateway__pb2.GetStudentScheduleResponse.SerializeToString,
            ),
            'GetSectionRoster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSectionRoster,
                    request_deserializer=week09__gateway__pb2.GetSectionRosterRequest.FromString,
                    response_serializer=week09__gateway__pb2.GetSectionRosterResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=week09__gateway__pb2.CreateAccountRequest.FromString,
                    response_serializer=week09__gateway__pb2.CreateAccountResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=week09__gateway__pb2.GetAccountRequest.FromString,
                    response_serializer=week09__gateway__pb2.GetAccountResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=week09__gateway__pb2.TransferRequest.FromString,
                    response_serializer=week09__gateway__pb2.TransferResponse.SerializeToString,
            ),
            'CreateInventoryItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInventoryItem,
                    request_deserializer=week09__gateway__pb2.CreateInventoryItemRequest.FromString,
                    response_serializer=week09__gateway__pb2.CreateInventoryItemResponse.SerializeToString,
            ),
            'ReserveItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveItem,
                    request_deserializer=week09__gateway__pb2.ReserveItemRequest.FromString,
                    response_serializer=week09__gateway__pb2.ReserveItemResponse.SerializeToString,
            ),
            'ReleaseReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseReservation,
                    request_deserializer=week09__gateway__pb2.ReleaseReservationRequest.FromString,
                    response_serializer=week09__gateway__pb2.ReleaseReservationResponse.SerializeToString,
            ),
            'GetInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventory,
                    request_deserializer=week09__gateway__pb2.GetInventoryRequest.FromString,
                    response_serializer=week09__gateway__pb2.GetInventoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'week09.Week09Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('week09.Week09Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Week09Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/CreateSection',
            week09__gateway__pb2.CreateSectionRequest.SerializeToString,
            week09__gateway__pb2.CreateSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/Enroll',
            week09__gateway__pb2.EnrollRequest.SerializeToString,
            week09__gateway__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/Drop',
            week09__gateway__pb2.DropRequest.SerializeToString,
            week09__gateway__pb2.DropResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/GetStudentSchedule',
            week09__gateway__pb2.GetStudentScheduleRequest.SerializeToString,
            week09__gateway__pb2.GetStudentScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSectionRoster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/GetSectionRoster',
            week09__gateway__pb2.GetSectionRosterRequest.SerializeToString,
            week09__gateway__pb2.GetSectionRosterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/CreateAccount',
            week09__gateway__pb2.CreateAccountRequest.SerializeToString,
            week09__gateway__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/GetAccount',
            week09__gateway__pb2.GetAccountRequest.SerializeToString,
            week09__gateway__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/Transfer',
            week09__gateway__pb2.TransferRequest.SerializeToString,
            week09__gateway__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInventoryItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/CreateInventoryItem',
            week09__gateway__pb2.CreateInventoryItemRequest.SerializeToString,
            week09__gateway__pb2.CreateInventoryItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/ReserveItem',
            week09__gateway__pb2.ReserveItemRequest.SerializeToString,
            week09__gateway__pb2.ReserveItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/ReleaseReservation',
            week09__gateway__pb2.ReleaseReservationRequest.SerializeToString,
            week09__gateway__pb2.ReleaseReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/week09.Week09Gateway/GetInventory',
            week09__gateway__pb2.GetInventoryRequest.SerializeToString,
            week09__gateway__pb2.GetInventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
